# This workflow is triggered by a push to the `main` branch
# which it checks out, minimises the appropriate html/css/js
# in-place, and pushes the changes to the `gh-pages` branch

# Inspired by: https://stackoverflow.com/a/73882805/11035513

name: minify-assets
run-name: minify assets

# Run on pushes to `release` branch
on:
  push:
    branches:
      - release

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install NodeJS and CLI tools
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # - run: npm install -g terser
      - run: npm install -g csso-cli
      - run: npm install -g html-minifier
      - run: npm install -g svgo

      # Perform minification, overwriting original files
      # - run: terser ./js/file.js --compress --mangle -o ./js/file.js
      - run: csso ./styles/reset.css -o ./styles/reset.css
      - run: csso ./styles/style.css -o ./styles/style.css
      # Get a list of CSS files starting with "font-"
      - run: css_font_files=$(find ./styles -name 'font-*.css')
      # Loop through the files and run csso for each file
      - run: |
          for file in $css_font_files; do
          echo "Minifying $file"
          csso ./styles/$file -o ./styles/$file
          done
      - run: html-minifier --case-sensitive --collapse-boolean-attributes --collapse-whitespace --minify-css --minify-js --minify-urls --remove-attribute-quotes --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --use-short-doctype -o index.html index.html
      - run: svgo -f ./images -o ./images

      # (Force) push changes to `gh-pages` branch
      - run: |
          git config user.name stepanjakl
          git config user.email stepanjakl@outlook.com
          git commit -am 'Automated minify of ${{ github.sha }}'
          git push --force -u origin release:gh-pages
